### ISSUE TITLE
[installation] tmforumodacanvas/component-istio-controller:0.3.2 is not available on DockerHub

### ISSUE THREAD

**Issue by fpapon** [tmforum-oda/oda-canvas#103]
## Long story short

Referenced version is not available on DockerHub

## Description

When installing the canvas in a fresh k8s cluster, the deployment of the tmforumodacanvas/component-istio-controller:0.3.2 is in error due to image pulling.

Failed to pull image "tmforumodacanvas/component-istio-controller:0.3.2": rpc error: code = Unknown desc = Error response from daemon: manifest for tmforumodacanvas/component-istio-controller:0.3.2 not found: manifest unknown: manifest unknown.

From here:
https://github.com/tmforum-oda/oda-canvas/blob/d8556e0cb76edb3aaad84d24b7f8e209749faa68/installation/canvas-oda/values.yaml#L111

The latest version available on DockerHub:
https://hub.docker.com/r/tmforumodacanvas/component-istio-controller/tags

The Values.yaml needs to be downgrade to 0.3.1 or the 0.3.2 has to be published on DockerHub to fix the deployment.

**Comment by LesterThomas** [comment]
The image has been added to DockerHub https://hub.docker.com/layers/tmforumodacanvas/component-istio-controller/0.3.2/images/sha256-f943c699208cb79f4c6999d0f06acac5cfa0bc1b4c22669be73532d171c1dcb5?context=explore

**Comment by fpapon** [comment]
@LesterThomas Thanks!
