### ISSUE TITLE
operator: publishedEvents & subscribedEvents v1beta3

### ISSUE THREAD

**Issue by peeterko2** [tmforum-oda/oda-canvas#104]
## Description

Fix the operators & CDR to support addtional attributes alligned with Published Component specification v1beta2/3

For publishedEvents:
- name: should use the AsyncAPI naming convention for topics TMFxxx.entity.notification
- apiType: currently only openapi (future extension could include asyncapi)
- hub: URL of the endpoint for registering callbacks
- port: 
- specification: swagger
- description: for documentation purpose in the canvas

For subscribedEvents:
- name: should use the AsyncAPI naming convention for topics TMFxxx.entity.notification
- apiType: currently only openapi (future extension could include asyncapi)
- callback: URL of the endpoint for receiving notificatons (removed '-' from v1beta2 spec)
- port: 
- specification: swagger
- description: for documentation purpose in the canvas

**Comment by peeterko2** [comment]
@soaserele: use this issue for submitting the fix

**Comment by csotiriou** [comment]
Hello, continuing from #90 , could I propose the addition of the following to the standard for the event mechanisms?

- A 'validations' property, which would be valuable as a reference to a set of validations to be done in the published - subscribed event
  - As a possible implementation, I would imagine that the validations property could be an array of `ConfigMap` references that contain JSON Schema validations for a specific event type.
- `x-kubernetes-preserve-unknown-fields: true` for the cases that cannot be covered by the mechanism beforehand
