### ISSUE TITLE
Documentation: Improvements to installation and other documentation from Innovation Hub onboarding

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#140]
## Description

This issue is to capture  improvements to installation and other documentation from Innovation Hub onboarding. There will be a related feature branch `issue-138-documentation-improvements` - we encourage any new team members onboarding onto ODA Canvas work to contribute documentation improvements to help others.

**Comment by thomo** [comment]
Just created a first PR with some improvements: 
https://github.com/tmforum-oda/oda-canvas/pull/145
