### ISSUE TITLE
dev: add dev container to ease local development

### ISSUE THREAD

**Issue by thomo** [tmforum-oda/oda-canvas#157]
## Description

To ease local development, we can add a [development container](https://containers.dev/) to your repository. A development container provides a consistent and isolated environment for your project, ensuring that all dependencies and tools required for development are readily available.

By adding a development container, we also can ensure that your development environment is consistent across different machines and easily shareable with other developers. It also helps in isolating dependencies and avoids conflicts with the host system.

**Comment by LesterThomas** [comment]
I like the approach to containerize the dev environment. Should we target to add tome of the canvas utilities to the dev container image (to make them available by default). At the moment there are 2 simple utilities to help with troubleshooting at [oda-canvas/source/utilities](https://github.com/tmforum-oda/oda-canvas/tree/master/source/utilities).  I had imagined that eventually we would have a canvas CLI with all the CTK and other utilities embedded into it.

**Comment by thomo** [comment]
> Should we target to add some of the canvas utilities to the dev container image (to make them available by default). At the moment there are 2 simple utilities to help with troubleshooting at [oda-canvas/source/utilities](https://github.com/tmforum-oda/oda-canvas/tree/master/source/utilities). 

Good idea - lets check how to do it
