### ISSUE TITLE
canvas-in-a-bottle: maintain or delete

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#162]
## Description

[Canvas-in-a-bottle](https://github.com/tmforum-oda/oda-canvas/tree/master/installation/canvas-in-a-bottle) is designed to be a very lightweight implementation of the ODA Canvas for developer and demonstration purposes. It runs the whole canvas in a [Kind](https://kind.sigs.k8s.io/) docker image.

Having this as a separate installation to the standard installation requires additional maintenance (to bring it up-to-date with the latest canvas features). We should either commit to maintaining this (and ideally make canvas-in-a-bottle deployments automated as part of the standard canvas testing), or delete this.

**Comment by brian-burton** [comment]
My inclination is to archive/delete the canvas-in-a-bottle.

When it was created we had lots of problems repeatably deploying a canvas, but work done by several team members means that we no longer have the same challenges and the Innovation Hub itself will help us solve any outstanding problems with the canvas.

The canvas-in-a-bottle was a useful tool at the time, but in my opinion it has served its purpose and is no longer required. Maintaining it adds complexity.
