### ISSUE TITLE
Canvas-Portal: Need to run canvas-portal inside the Canvas namespace

### ISSUE THREAD

**Issue by aankursarkar** [tmforum-oda/oda-canvas#174]
## Description

As Canvas-portal is a part of Canvas services, so we are planning to run Canvas-portal within the Canvas namespace. Therefore, we deployed Canvas-portal inside the Canvas namespace, but it seems it hasn't established the connection with the running ODA components deployed inside the components namespace on the same cluster and is showing a blank page over Canvas-portal. Please find the screenshot below.

So, we need to modify the Canvas-portal code to run within the Canvas namespace. It would also be nice to have the connection string configurable via application.properties or environment variables.

https://github.com/tmforum-oda/oda-canvas/tree/master/canvas-portal

Canvas Portal deployed inside canvas namespace over Innovation Hub GKE cluster --> Portal running, but running ODA component don't show over UI.
http://34.147.16.170:8080/canvas-portal/index.html

![image](https://github.com/tmforum-oda/oda-canvas/assets/29706990/b6959a75-0a4f-492a-a9f3-28859244c5f2)
 
Canvas Portal deployed inside components namespace over Innovation Hub GKE cluster --> Working as expected.
http://35.234.166.145:8080/canvas-portal/index.html

![image](https://github.com/tmforum-oda/oda-canvas/assets/29706990/9ed882c7-0a0c-4e5d-8ecf-7450f27cbd00)

**Comment by wangyumu** [comment]
The Canvas-Portal currently defaults to using the `components` namespace, but given that it's a service within the Canvas platform, it would indeed be more appropriate to use the `Canvas` namespace. I agree with your suggestion. Let's proceed with creating a Pull Request to transition to the `Canvas` namespace.
