### ISSUE TITLE
GitHub action error: Automatic labelling (and approval for certain types of PR) fails

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#188]
## Description

The GitHub action [label-pullrequest](https://github.com/tmforum-oda/oda-canvas/blob/master/.github/workflows/label-pullrequest.yml) is failing for all Pull Requests. I suspect that the GitHub API has been deprecated. 

This issue is to either fix the issue or remove this action.

**Comment by thomo** [comment]
@LesterThomas have you seen #186? I assume an issue with the repo origin.

**Comment by LesterThomas** [comment]
> @LesterThomas have you seen #186? I assume an issue with the repo origin.

I think for now I will just remove this automatic labelling.
