### ISSUE TITLE
Repo: add badges to releases

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas#205]
## Add badges to releases
For each [release](https://github.com/tmforum-oda/oda-canvas/releases) we should add badges that show the status of TDD tests at the point the release was made.

**Comment by anshulkumar-tmf** [comment]
As per planning: 
done, to be confirmed with Suyash, add comments about what was done, Cucumber report account to be updated to TM Forum, Adarsh to Confirm
