### ISSUE TITLE
Feature: Create BDD features for the Component Lifecycle Management

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#221]
## Description

As part of making the ODA Canvas more modular, we have separated out the Component Lifecycle management (see use case [002](https://github.com/tmforum-oda/oda-canvas/blob/8e7a98eedc233637fa9420bf93ad81b3ac47b6b9/usecase-library/UC002-Manage-Components.md)).

This issue is to create a set of features describing the desired behavior for the Component Lifecycle Management.

**Comment by pecanpete** [comment]
I will update teh slides we used on teh end to end process for BDD -. TDD and use term steps definition/specification do we need to change folder names on Github e.g. compliance-test-kit/BDD-and-TDD  https://github.com/ODA-CANVAS-FORK/oda-canvas-component-vault/tree/master/compliance-test-kit/BDD-and-TDDhttps://github.com/ODA-CANVAS-FORK/oda-canvas-component-vault/tree/master/compliance-test-kit/BDD-and-TDD
