### ISSUE TITLE
Naming convention for Canvas Operators

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#223]
## Description

We should have a standard naming convention for Canvas Operators to ensure clarity and consistency. The proposal is to use:

* **\<Noun\> Management** for operators that are managing individual resources.
* **\<Noun\> Config** for operators that are setting-up and configuring the common service exposed by the canvas. 
* **\<Noun\> Control** for operators that are setting up mechanisms where the canvas is enabling components to control some aspects of their behavior. 

## Rationale

We have some Canvas Operators that manage individual resources (for example the Exposed APIs or Published Notifications). These should be called **\<Noun\> Management** operators. 

We have other Canvas Operators that only configure the associated common services (for example the **Identity Config Operator** is setting up a mechanism for handling identities). These should be called **\<Noun\> Config** operators. 

We have other Canvas Operators that are setting up control mechanisms (for example for **Cost Control** or **Carbon Control**). These operators set-up mechanisms where a canvas will offer services towards components that enable those components to control their behavior. The canvas may also provide data for analysis. These should be called **\<Noun\> Control** operators.

This follows common naming patterns used in the wider Operator ecosystem.

## Implication

We need to re-name some of the existing operators and the use-cases that use these names. We will also create a markdown file with this naming convention. The names will be (for current operators):

| Old Name             | New Name                     |
| -------------------- | ------------------------------- |
| Component Management Operator | Component Lifecycle Management Operator |
| API Management Operator | API Management Operator  |
| Event Management Operator     | Event Management Operator |
| Identity Management Operator  | Identity Config Operator |
| Observability Management Operator | Observability Config Operator |
| Secrets Management Operator | Secrets Management Operator |
| Carbon Management Operator    | Carbon Control Operator |
| Cost Management Operator      | Cost Control Operator  |

**Comment by ferenc-hechler** [comment]
In our logical view we made a distiction between ComponentVaultProvider and ComponentVaultOperator.

**Component-vault provider**
provisions the component specific vaults based on the extracted ComponentVault CRD

**Component-vault operator**
injects the sidecar for seamles communication with the ComponentVault. Authentication is handled automatically by Kubernetes Service-Account Tokens (JWT)

Based on this functionality we could rename ComponentVaultProvider to Secrets-Config-Operator.
But we need another name for ComponentVaultOperator

![image](https://github.com/tmforum-oda/oda-canvas/assets/11094156/96f4df1f-aed9-4a5e-af44-86d217bbcd3f)
![image](https://github.com/tmforum-oda/oda-canvas/assets/11094156/f93fa168-05e8-4b0f-886f-bf4aa6a35f20)

**Comment by ferenc-hechler** [comment]
Discussed this in todays Tech/Arch meeting and we stick to the previous name "Secrets-Management-Operator".

**Comment by LesterThomas** [comment]
@ferenc-hechler - I'm going through and renaming the operators to align to this issue. For the technology-specific operators, I'm proposing to name the operator as above with a postfix of `-<technology>`. e.g. the `apiOperatorKong` will become `apiManagementOperator-Kong`.

Your `secretsmanagementOperator-hc` will become `secretsManagementOperator-Vault`. Is this OK with you?

**Comment by LesterThomas** [comment]
Fixed in #409
