### ISSUE TITLE
Feature: Adding Existing Permission Specification Sets in the component to identity platform.

### ISSUE THREAD

**Issue by adarshkumar4** [tmforum-oda/oda-canvas#229]
This issue is to add a BDD feature (in [feature-definition-and-test-kit/features](https://github.com/tmforum-oda/oda-canvas/tree/master/feature-definition-and-test-kit/features)) for Feature: Grouping Permission Specification Sets into Business Roles in Identity Management Solution.

This BDD would cover adding existing permission specification sets in the component to identity platform.

This links to [issue #82](https://github.com/tmforum-oda/oda-canvas/issues/82).

**Comment by pecanpete** [comment]
Which sequence charts would this relate to? Trying to understand what Component or canvas Operator service operator is exposing this feature . We generally have taken the view that use cases sequence charts should explicitly define features and BDD are then testing those feature scenarios  see https://github.com/tmforum-oda/oda-canvas/tree/master/usecase-library/pumlFiles  for the current ODA CA sequence chart . If i am not mistaken we need a sequence chart explaining the context of the feature for which you want  a BDD. We do have a ODA C&C activity which is similar to ODA CA see https://projects.tmforum.org/wiki/pages/viewpage.action?pageId=278562058  which is being developed by the ODA Security and Privacy team. Difference is that it is not K8S specific Happy to discuss this further.

**Comment by adarshkumar4** [comment]
I think it relates to configure-users-and-roles sequence chart.
