### ISSUE TITLE
GitHub action: Run chart-releaser failing due to chart.lock file error

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#235]
## Description

The Run chart-releaser GitHub action is failing due to chart.lock file error
![image](https://github.com/tmforum-oda/oda-canvas/assets/7374014/cd95e912-4bad-4dd4-ba6e-68d95b7b6e61)

This is happening even though the `Chart.lock` appears to have the same dependencies as the `Chart.yaml`

**Comment by ferenc-hechler** [comment]
Maybe there is missing a helm dependency build in the new "dependentapi-simple-operator" chart.

**Comment by LesterThomas** [comment]
I've tested the GitHub actions in my own fork https://github.com/LesterThomas/oda-canvas 

I managed to get the GHActions working by removing the .lock file from https://github.com/tmforum-oda/oda-canvas/tree/master/charts/api-gateway
(I've no idea why it was failing as the .lock file looked to have the same dependencies as the .yaml file).

I'll contribute this fix as a PR - I'm planning to include manually recreating the images in https://hub.docker.com/orgs/tmforumodacanvas/ at the same time

**Comment by ferenc-hechler** [comment]
Maybe I misunderstood how to maintain those files. I commited my local charts.lock file after I deployed from my local filesystem. Should I avoid checking in the lock file?

**Comment by LesterThomas** [comment]
It is generally considered good practice to commit the `Chart.lock` files to the repository. Committing the `Chart.lock` files ensures that the exact versions of the dependencies are pinned, which helps in maintaining consistency across different environments and builds.
See [should-helm-dependencies-charts-folder-be-version-controlled](https://stackoverflow.com/questions/73599035/should-helm-dependencies-charts-folder-be-version-controlled). 

This practice prevents issues that may arise from dependency updates or changes that could occur if the dependencies were not pinned.

Committing `Chart.lock` files helps to:

* Ensure reproducibility of builds.
* Maintain consistency across different environments.
* Avoid unexpected changes in dependencies.

**Comment by LesterThomas** [comment]
I think the issue we are experiencing is due to the Chart Releaser action not working well when some of the charts have not been updated. This requires further investigation.

**Comment by LesterThomas** [comment]
I haven't been able to recreate this issue (and it hasn't happened since). Closing issue
