### ISSUE TITLE
component: Add SecretsManagement section to main component CRD?

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#258]
## Description

There is a [SecretsManagement](https://github.com/tmforum-oda/oda-canvas/blob/master/charts/oda-crds/templates/oda-secretsmanagement-crd.yaml) CRD that defines the requirement of a component for a Secrets Management capability.

This issue is to:

* add the Secrets Management into the main Component CRD as an optional property under the Security section. 
* update the Component Operator to automatically create the SecretsManagement CRD for a component is it uses the Secrets Management capability.

**Comment by ferenc-hechler** [comment]
Oops, looks like we missed something.
It should be the same is in the secretsmanagement crd:
https://github.com/tmforum-oda/oda-canvas/blob/6ee835a1609b707d011d799a95047aa64c0d1d24/charts/oda-crds/templates/oda-secretsmanagement-crd.yaml#L27-L55
I will create a PR for adding this

**Comment by ferenc-hechler** [comment]
created PR #259
