### ISSUE TITLE
1Beta4 Schema

### ISSUE THREAD

**Issue by hvaughanattmforum** [tmforum-oda/oda-canvas#260]
TAC-880	Update component template	

Please include the ask in Jira TAC 880 in the next iteration of the YAML Schema.

**Comment by LesterThomas** [comment]
Adding details from https://projects.tmforum.org/jira/browse/TAC-880

Overall:
Change the order to the different blocks (e.g. dependentAPIs,  exposedAPIs:, etc..) to be aligned with the functional specification
Event section:
Add: id, version (for the API)
Remove: name (for the API, it should be resolved at publication time as the API name for the dependentAPIs,  exposedAPIs)
Metadata:
Evaluate new block with:
description
functionalBlock
id
mantainers
publicationDate
status
version

**Comment by LesterThomas** [comment]
@hvaughanattmforum - there is no problem with changing the ordering of properties in the Schema definition in GitHub. Please note that properties in a YAML document are officially unordered, and so if you pass a YAML document into and out of many tools, the order may change!

**Comment by hvaughanattmforum** [comment]
Thanks.

And the consolidation of the metadata into one block?  It's shattered between all the configuration content.

Metadata:
Evaluate new block with:
description
functionalBlock
id
maintainers
publicationDate
status
version

**Comment by LesterThomas** [comment]
Yes - I like the idea of putting this metadata into a block to group it. The word 'metadata' is already used in Kubernetes for something else! Any idea of what to call the block?

**Comment by hvaughanattmforum** [comment]
Hi Lester

componentData?
componentDescription?

Content?

No sure what is culturally appropriate.
