### ISSUE TITLE
BDD: Features and scenarios to test dependent APIs

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#290]
## Description

Create a set of BDD features and scenarios to test dependent APIs. Use the example component from  [reference-example-components issue 18](https://github.com/tmforum-oda/reference-example-components/issues/18) to build the scenarios.

**Comment by anshulkumar-tmf** [comment]
Hi @LesterThomas,

Is this issue same as https://github.com/tmforum-oda/oda-canvas/issues/365

**Comment by LesterThomas** [comment]
Fixed in #383
