### ISSUE TITLE
Usecase: Update UC007-Configure-Dependent-APIs for Canvas.Info

### ISSUE THREAD

**Issue by LesterThomas** [tmforum-oda/oda-canvas#303]
## Description

Update Usecase library [UC007-Configure-Dependent-APIs](https://github.com/tmforum-oda/oda-canvas/blob/master/usecase-library/UC007-Configure-Dependent-APIs.md) based on the decision to use Canvas.Info service (see issue #208)

**Comment by ferenc-hechler** [comment]
Together with @brian-burton we created a sketch how the Data Flow looks like

![image-2024-08-28-15-50-56-990](https://github.com/user-attachments/assets/9881ee1d-44d5-4860-b349-39e3834a66a9)
