### ISSUE TITLE
Istio Ingress: add self-signed certificates and default to TLS

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas#329]
## Add self-signed certificates and default to TLS for Istio Ingresses

For Istio Ingress, add self-signed certificates by default to all ExposedAPI endpoints and ensure that the ExposedAPI endpoint metadata uses the HTTPS URL.

**Comment by anshulkumar-tmf** [comment]
As per planning, This issue can be closed.
@brian-burton , @RJ-acc
