### ISSUE TITLE
API Management Operator: Add enforcement of component authentication in the API gateway

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas#335]
### Explanation
At the moment there's no authentication of any component. This issue ensures that, by default, any component that hits the Canvas API gateways will be authenticated. Some components won't have authentication enabled and will need to be allowed for testing without authentication, but that should be a conscious decision.

### What feature functionality/tasks does this issue cover?
- Default authentication via authorisation code flow and client credentials flow
- The ability to disable authentication if required.
- Documentation of authentication flows and how to integrate components with the Canvas.

### Provisional BDD
- Given a component with 1 or more ExposedAPIs is installed
- When an unauthenticated consumer calls an ExposedAPI
- Then the API Gateway should enforce authentication of the consumer

**Comment by anshulkumar-tmf** [comment]
As per planning: Functionally in place, check documentation maturity, configurability (on/off), confirm test steps

**Comment by RJ-acc** [comment]
BDD work also done for Both kong and apisix - https://github.com/tmforum-oda/oda-canvas/pull/415. @brian-burton  can we close this issue now?
