### ISSUE TITLE
DevExperience: Add automated vulnerability scan for container images

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas#345]
### Explanation
To provide our users with some level of assurance of quality, we need to make sure the images we create are vulnerability checked as part of the release.

### What feature functionality/tasks does this issue cover?
- A decision on what constitutes a vulnerability test
- Automation of the vulnerability test
- Inclusion of test results in release notes
- (Optionally) Automated reporting of vulnerabilities as new issues

### Provisional BDD
- Given a pull request that will result in a new container being built
- When the pull request is tested
- Then the container image will be vulnerability tested

**Comment by anshulkumar-tmf** [comment]
Hi @brian-burton ,

Does the PR https://github.com/tmforum-oda/oda-canvas/pull/361 cover this issue?
