### ISSUE TITLE
Issues while installing Canvas on top of ARM architecture

### ISSUE THREAD

**Issue by IremGA** [tmforum-oda/oda-canvas#411]
## Long story short

Hi, 

I'm trying to the new version of canvas and facing an issue with **quay.io/appuio/oc:v4.14** image while running job 
canvas-sm-preinst-autodetect-audience-9ks45. 
Error is :  Failed to pull image "quay.io/appuio/oc:v4.14": no matching manifest for linux/arm64/v8 in the manifest list entries

I'm following these steps : 

1. Starting Colima VM using AMD arch : 
    colima start --cpu 4 --memory 16 --arch x86_64-v2 --kubernetes --kubernetes-version v1.29.11-rc1%2Bk3s1 

2. After Colima local cluster starts, I'm applying below steps without any issue : 
cd Documents/GitHub/oda-canvas
  277  ./installation/precheck.sh
  278  helm plugin install --version "main" https://github.com/Noksa/helm-resolve-deps.git
  279  helm repo add jetstack https://charts.jetstack.io\nhelm repo add bitnami https://charts.bitnami.com/bitnami
  280  helm repo add istio https://istio-release.storage.googleapis.com/charts
  281  helm repo update
  282  kubectl create namespace istio-system
  283  helm install istio-base istio/base -n istio-system
  284  helm install istiod istio/istiod -n istio-system --wait
  285  kubectl create namespace istio-ingress
  286  kubectl label namespace istio-ingress istio-injection=enabled
  287  helm install istio-ingress istio/gateway -n istio-ingress --set labels.app=istio-ingress --set labels.istio=ingressgateway --wait

3. Then I'm running below commands and Canvas deployment is failing : 
  helm repo add oda-canvas https://tmforum-oda.github.io/oda-canvas
  helm install canvas oda-canvas/canvas-oda -n canvas --create-namespace --timeout 15m
Result : 
Error: INSTALLATION FAILED: failed pre-install: 1 error occurred:
        * timed out waiting for the condition
        
Note: **I was able to install v1beta3 Canvas using above commands**. However v1beta4 can not be installed. 

Python Version : 3.13.0
Kubernetes version : v1.29.11
Docker version: 27.3.1

![image](https://github.com/user-attachments/assets/b64f264d-e258-496a-8857-12ab386084ba)

Thanks!

## Description

<details><summary>The code snippet to reproduce the issue</summary>

```python
import kopf
```
</details>

<details><summary>The exact command to reproduce the issue</summary>

```bash
kopf run ...
```
</details>

<details><summary>The full output of the command that failed</summary>

```
```
</details>

## Environment

* Kopf version: 
* Kubernetes version: 
* Python version: 
* OS/platform: Apple M2 Pro MAC OS 14.5 (23F79)

<details><summary>Python packages installed</summary>

```
```
</details>

**Comment by LesterThomas** [comment]
I think this is an issue with an addition we made to do pre-install checks (the `canvas-sm-preinst-autodetect-audience` is part of this check). @RJ-acc , @ajayaggarwal03  can you review?

**Comment by gusjer** [comment]
This sounds related to #378 . That image was replaced by @ferenc-hechler  with a custom one [here ](https://github.com/tmforum-oda/oda-canvas/blob/51fd8104ce94199150a530390bedb15812e05cf5/charts/secretsmanagement-operator/templates/preinst-autodetect-audience-job.yaml#L31). Maybe you are trying to install from a stale branch

**Comment by IremGA** [comment]
Thanks for your replies. I'm using **master** branch of the repository.

**Comment by ferenc-hechler** [comment]
Sorry, looks like the fix was not yet released.
Most likely we will make a release of Canvas version 1.1.8 on Monday and then this quay.io image will not be used any more.

As an alternative you can install the Canvas from the helm charts of the master branch:

```
helm repo add jetstack https://charts.jetstack.io
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add hashicorp https://helm.releases.hashicorp.com
helm repo update

cd ~/git/oda-canvas
helm dependency update --skip-refresh ./charts/cert-manager-init
helm dependency update --skip-refresh ./charts/canvas-api-gateway/combined-api-gateway-chart
helm dependency update --skip-refresh ./charts/canvas-vault
helm dependency update --skip-refresh ./charts/canvas-oda

helm upgrade --install canvas charts/canvas-oda -n canvas --create-namespace 
```

**Comment by ferenc-hechler** [comment]
v1.1.8 was released today.
So, ARM architecture should now be supported when installing from the public helm charts.
