### ISSUE TITLE
Unable to install oda-canvas locally by following the documentation

### ISSUE THREAD

**Issue by csotiriou** [tmforum-oda/oda-canvas#43]
Hello, not sure if this is a bug or if there is something I miss from the documentation. I am trying to install the oda-canvas locally using microk8s by following the instructions here:

When I reach the point where I'm calling `bash install_canvas_cert-manager.sh`, I am being shown the following message:

```
*********************************************************************
Installing base canvas
*********************************************************************

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "odacomponent-role-cluster" namespace: "" from "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "odacomponent-rolebinding-cluster" namespace: "" from "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "odacomponent-role-namespaced" namespace: "components" from "": no matches for kind "Role" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "odacomponent-rolebinding-namespaced" namespace: "components" from "": no matches for kind "RoleBinding" in version "rbac.authorization.k8s.io/v1beta1"
ensure CRDs are installed first, resource mapping not found for name: "component-gateway" namespace: "components" from "": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
ensure CRDs are installed first]
```

It seems that there are some CRDs that I haven't got installed. Is there anything I am missing from the documentation, or is there some other repository where those CRDs are available so that I can install them first?

This is the output from running `microk8s kubectl version`
```
$ microk8s kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.16-3+024782121eb186", GitCommit:"024782121eb1866f575ad5d06b5b58722e76d29c", GitTreeState:"clean", BuildDate:"2022-11-10T18:14:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```

Thank you in advance

**Comment by gjo-satec** [comment]
Hi, I can see two problems there.
The Canvas has struggled to keep up with changes in Kubernetes, ClusterRole,Role, and so[, left the Beta status in 1.22 ](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#rbac-resources-v122) and you seem to use just that exact version 
The last error seems similar, but it's. The latest version I played with relied on Istio and its Gateway object instead the already provided by default Ingress
The documentation asks us to install that kind of dependency. Istio is a Service Mesh implementation, but we probably need to be more evident now that this dependency is mandatory. 
["If the canvas is relying on other underlying services (e.g. Service Mesh) then these should be deployed in advance of the canvas itself."](https://github.com/tmforum-oda/oda-canvas-charts#prerequisites)

**Comment by gjo-satec** [comment]
It looks like the previous installation attempt leaves things installed
The bash is a convenience wrapper for mostly helm commands, 
You can try to execute this before trying again
`helm uninstall --namespace canvas canvas`
It should uninstall the remains of previous installations , I guess

If you faced more errors, I would try to start with a clean installation of Kubernetes, although I'm not too optimistic about using newer versions of Kubernetes.

**Comment by 9n** [comment]
The same problem with k3s installation.

**Comment by 9n** [comment]
This issue should be closed.
