### ISSUE TITLE
Feature: Component-Specified Rate Limiting and Throttling of API Requests

### ISSUE THREAD

**Issue by brian-burton** [tmforum-oda/oda-canvas#80]
##Description

This issue is to add a BDD feature (in [compliance-test-kit/BDD-and-TDD/features](https://github.com/tmforum-oda/oda-canvas/tree/master/compliance-test-kit/BDD-and-TDD/features) ) for **Feature: Component-Specified Rate Limiting and Throttling of API Requests**.

This is from the authentication workshop:

`We need to be able to rate limit/throttle authentication requests`

This does not currently link to a decision in the [Decision Log](https://github.com/tmforum-oda/oda-ca-docs/tree/master/Decision-Log).

**Comment by RJ-acc** [comment]
Work completed and BDD also in place for Kong/Apisix . BDD will run conditionally like if canvas  deployed with kong, apisix BDDs will be skipped and kong will run and vice-versa.  https://github.com/tmforum-oda/oda-canvas/pull/415.  @brian-burton  Please confirm if we can close this issue.
<img width="416" alt="image" src="https://github.com/user-attachments/assets/26b34522-955e-423f-aaee-3240447929a7">

**Comment by LesterThomas** [comment]
Closed in #415
