### ISSUE TITLE
Feature:Canvas support arm64 cpu architecture

### ISSUE THREAD

**Issue by shisen1** [tmforum-oda/oda-canvas#86]
Canvas's current version does not support the arm64 CPU architecture. When deploying Canvas on a machine with an arm64 architecture, you may encounter some exceptions, such as "exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error." The affected services include keycloak, keycloak-config-cli, postgresql, tmforumodacanvas/component-istio-controller and tmforumodacanvas/security-listener. To support arm64 and amd64 both CPU architecture, you can take the following steps:

1. For keycloak, keycloak-config-cli, and postgresql, the images themselves can support the arm64 architecture by upgrading their versions. Upgrading to a newer version should provide arm64 and amd64 both support.
2. For tmforumodacanvas/component-istio-controller and tmforumodacanvas/security-listener, which are Canvas's own applications, you will need to use the "docker buildx" command to build arm64 and amd64 images and upload them to Docker Hub.

**Comment by csotiriou** [comment]
I would add that there is also the webhook that needs to be updated as well. https://github.com/tmforum-oda/oda-canvas/tree/master/installation/oda-webhook. I'm currently using a docker image of mine that is multi-arch, I would love to update the original if I have access to it.
